import type { Metadata } from "next";
import {Orbitron, Titillium_Web } from "next/font/google";
import "./globals.css";


const titillium = Titillium_Web({
  subsets: ["latin"],
  variable: "--font-titillium", 
  weight: ["300", "400", "600", "700"], 
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titillium.variable} ${orbitron.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
